swagger: '2.0'
info:
  version: '1.0'
  title: "Test api"
  description: Get info on courses
  license:
    name: MIT
    url: www.google.it
host: herokuapp.com
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /courses:
    x-summary: Courses management
    get:
      summary: List all courses
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Course'
          examples:
            application/json:
              - id : 11
                name: 'c1'
              - id: 33
                name: 'string'
    post:
      description: Create a course
      summary: Create a course
      parameters:
        - name: course_name
          in: body
          required: true
          schema:
            type: integer
      responses:
        201:
          description: 'pippo'
          schema:
            $ref: '#/definitions/Course'
          examples:
            application/json:
              id: 38
              name: 'ugo'
definitions:
  Course:
    title: some title
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
    required:
      - id
      - name